name: 'Gosec Security Checker'
description: 'Runs the gosec security checker'
author: '@ccojocar'

inputs:
  args:
    description: 'Arguments for gosec'
    required: true
    default: '-h'
  working-directory:
    description: "Current working directory, default is project root"
    required: false
    default:  '.'

runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
      - ${{ inputs.working-directory }}
      - ${{ inputs.args }}

branding:
  icon: 'shield'
  color: 'blue'
